FROM node:14 AS production-bundle
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run-script build

FROM nginx:stable-alpine AS production-server
WORKDIR /app
COPY --from=production-bundle /app/build /app
COPY deploy/local/nginx-server.conf /etc/nginx/conf.d/default.conf
